name: Docker Image CI

on:
  push: 
    branches:
      - master
      - cidev
jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Build
      working-directory: fluentd
      run: docker build -f Dockerfile . --tag image

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-duration-seconds: 900
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fluentd-windows
        IMAGE_TAG: "1809"
        LOCAL_IMAGE: image
      run: |
        $IMAGE_ID="$Env:ECR_REGISTRY/$Env:ECR_REPOSITORY"
        $REMOTE_TAG="${IMAGE_ID}:$Env:IMAGE_TAG"
        docker tag $Env:LOCAL_IMAGE $REMOTE_TAG
        Write-Host "pushing $REMOTE_TAG"
        docker push $REMOTE_TAG